### ISSUE TITLE
Managing, viewing, and applying to Jobs

### ISSUE THREAD

**Issue by Adamo-O** [jay-roe/Interlinked#179]
# Epic

### Description
This is an epic containing the user stories related to managing, viewing, and applying to jobs.

![image](https://user-images.githubusercontent.com/55419809/227795545-d57094e9-57a6-4edf-b388-fa13d0aacc0c.png)

Story points: 19
Priority: High
Risk: Medium
User stories:

- [x] #55 
- [x] #59 
- [x] #61 
- [x] #65 
- [x] #68 

### Acceptance Tests

- [x] Create company
- [x] Create job posting
- [x] Edit job posting
- [x] Delete job posting
- [x] Get job notification when related job posted
- [x] Search for job and get redirect to selected job
- [x] Store resume and cover letter on user account
- [x] Quick-apply to job using saved resume and/or cover letter
- [x] Apply to job position by uploading file(s) during application process
